### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by abhshkdsgh** [maniacx/Battery-Health-Charging#24]
Dark Mode on Ubuntu 22.10 doesn't get applied to this gnome-shell-extension.
Theme: Dracula (https://www.gnome-look.org/p/1687249) (For Shell & Legacy Applications).
I tried changing from light mode to dark mode also.
Using Asus Vivobook 15.

**Comment by abhshkdsgh** [comment]
![image](https://user-images.githubusercontent.com/128728755/230776225-f0e191c7-01b3-4335-ba4a-b879552b30bc.png)

**Comment by maniacx** [comment]
Can you post some screenshot. You can just drag or attach the screenshot file in the comment

**Comment by maniacx** [comment]
Ok I just tried the theme and the issue is not with my extension but with the theme. All other extension have the same issues and behave the same as my extension. The installation method suggested in the instructions is not enough to apply the theme properly, for gnome 40 and above. A quick search in the Dracula's themes issue I found the solution.

For Preference you need to copy all contents from gtk4 in ~/config/gtk4 folder as mentioned here https://github.com/dracula/gtk/issues/203#issuecomment-1486034571

For gnome shell fix is copy/replace files from v40 folder as mentioned here https://github.com/dracula/gtk/issues/124#issuecomment-875036340

But I am just assuming your problem,  since you havent mentioned what is the exact issue and I will leave this open.
Please give me more info and continue with your issue and close if the themes fixes works for you.

![Screenshot from 2023-04-09 17-59-04](https://user-images.githubusercontent.com/4295343/230800514-14e976ce-023b-492e-b2e8-038684bd7d38.png)
![Screenshot from 2023-04-09 17-59-40](https://user-images.githubusercontent.com/4295343/230800519-194e82c0-4908-4bde-b4a3-f29775b44f37.png)

**Comment by abhshkdsgh** [comment]
In quick settings only dark mode didn't get applied. 
I am sorry to raise the issue here. I should have noticed this is a problem with theme not with this extension.
The solution pointed out by @maniacx worked for me.
Thank you for helping me even when you could just delete this issue once you noticed it's not a problem with this extension.
